### ISSUE TITLE
[Feature Request] Making the "downloads add" folder and target optional

### ISSUE THREAD

**Issue by l0wl3vel** [AntonLydike/diggicamp#2]
Since the course names are most of the time pretty descriptive already, it would be easier to just make the argument optional and replace it with a flag.

It would be nice if there is no folder argument given to just download all the folders from a course.

**Comment by AntonLydike** [comment]
thanks for the idea. It's implemented as of cbd5e9d0870b7ca885952342a48679c5e1ee7425
